
### create a blog
post http://localhost:3003/api/blogs
Content-Type: application/json

{"title":"second post", "author":"antoine","url":"http://localhost","likes":0}

###

get http://localhost:3003/api/blogs

